import java.util.HashMap;
import java.util.Map;

public class AikoResponde {
    private int score = 0;
    private Map<String, String> diccionario = new HashMap<>();

    public AikoResponde() {
        inicializarTokens();
    }

    private void inicializarTokens() {
        // Carga de todas las palabras y etiquetas combinadas
        diccionario.put("a", "preposicion"); diccionario.put("abajo", "posicion");
        diccionario.put("acabamos", "accion"); diccionario.put("actual", "tiempo");
        diccionario.put("actualiza", "accion"); diccionario.put("además", "conector");
        diccionario.put("adentro", "posicion"); diccionario.put("algún", "indefinido");
        diccionario.put("algo", "indefinido"); diccionario.put("al", "preposicion");
        diccionario.put("ambigua", "adjetivo"); diccionario.put("asemos", "accion");
        diccionario.put("así", "adverbio"); diccionario.put("cuando", "tiempo");
        diccionario.put("cada", "distributivo"); diccionario.put("callado", "estado");
        diccionario.put("cambia", "accion"); diccionario.put("cambie", "accion");
        diccionario.put("captura", "accion"); diccionario.put("centrado", "estado");
        diccionario.put("clara", "adjetivo"); diccionario.put("como", "comparativo");
        diccionario.put("común", "adjetivo"); diccionario.put("completa", "estado");
        diccionario.put("completado", "estado"); diccionario.put("completamente", "adverbio");
        diccionario.put("completo", "estado"); diccionario.put("con", "preposicion");
        diccionario.put("conversación", "sustantivo"); diccionario.put("crea", "accion");
        diccionario.put("cuál", "interrogativo"); diccionario.put("da", "accion");
        diccionario.put("dame", "accion"); diccionario.put("dando", "accion");
        diccionario.put("de", "preposicion"); diccionario.put("decía", "accion");
        diccionario.put("definir", "accion"); diccionario.put("definitivamente", "adverbio");
        diccionario.put("del", "preposicion"); diccionario.put("diseño", "sustantivo");
        diccionario.put("dices", "accion"); diccionario.put("dile", "accion");
        diccionario.put("donde", "lugar"); diccionario.put("elegante", "adjetivo");
        diccionario.put("el", "articulo"); diccionario.put("ejemplo", "sustantivo");
        diccionario.put("emi", "nombre"); diccionario.put("encantó", "emocion");
        diccionario.put("entiendo", "cognitivo"); diccionario.put("es", "verbo");
        diccionario.put("escenario", "sustantivo"); diccionario.put("ese", "demostrativo");
        diccionario.put("esta", "demostrativo"); diccionario.put("estamos", "verbo");
        diccionario.put("estoy", "verbo"); diccionario.put("exacto", "afirmacion");
        diccionario.put("explicamos", "accion"); diccionario.put("fluya", "accion");
        diccionario.put("fondo", "sustantivo"); diccionario.put("favor", "peticion");
        diccionario.put("hagas", "accion"); diccionario.put("habrá", "verbo");
        diccionario.put("haces", "accion"); diccionario.put("hecho", "estado");
        diccionario.put("hey", "saludo"); diccionario.put("hola", "saludo");
        diccionario.put("igual", "comparativo"); diccionario.put("igualmente", "comparativo");
        diccionario.put("imitar", "accion"); diccionario.put("increíble", "adjetivo");
        diccionario.put("increíblemente", "adverbio"); diccionario.put("inferior", "posicion");
        diccionario.put("jugar", "accion"); diccionario.put("la", "articulo");
        diccionario.put("llama", "accion"); diccionario.put("lugar", "sustantivo");
        diccionario.put("lograr", "accion"); diccionario.put("más", "cantidad");
        diccionario.put("me", "pronombre"); diccionario.put("mete", "accion");
        diccionario.put("mismo", "identidad"); diccionario.put("muy", "intensificador");
        diccionario.put("necesitamos", "necesidad"); diccionario.put("necesito", "necesidad");
        diccionario.put("nunca", "negacion"); diccionario.put("no", "negacion");
        diccionario.put("nueva", "adjetivo"); diccionario.put("osea", "conector");
        diccionario.put("para", "preposicion"); diccionario.put("parte", "sustantivo");
        diccionario.put("pero", "conector"); diccionario.put("primera", "orden");
        diccionario.put("puede", "posibilidad"); diccionario.put("puedes", "posibilidad");
        diccionario.put("puedo", "posibilidad"); diccionario.put("poner", "accion");
        diccionario.put("ponerle", "accion"); diccionario.put("por", "preposicion");
        diccionario.put("que", "conector"); diccionario.put("quede", "estado");
        diccionario.put("quitalas", "accion"); diccionario.put("querés", "deseo");
        diccionario.put("rápido", "tiempo"); diccionario.put("real", "adjetivo");
        diccionario.put("repetiré", "accion"); diccionario.put("repitió", "accion");
        diccionario.put("repitieron", "accion"); diccionario.put("refieres", "accion");
        diccionario.put("rol", "sustantivo"); diccionario.put("roles", "sustantivo");
        diccionario.put("sabe", "cognitivo"); diccionario.put("se", "pronombre");
        diccionario.put("sepa", "cognitivo"); diccionario.put("ser", "verbo");
        diccionario.put("seré", "verbo"); diccionario.put("si", "condicional");
        diccionario.put("simplemente", "adverbio"); diccionario.put("sin", "negacion");
        diccionario.put("sistema", "sustantivo"); diccionario.put("solo", "cantidad");
        diccionario.put("suave", "adjetivo"); diccionario.put("te", "pronombre");
        diccionario.put("tenga", "verbo"); diccionario.put("tenés", "verbo");
        diccionario.put("tengo", "verbo"); diccionario.put("tiene", "verbo");
        diccionario.put("tienes", "verbo"); diccionario.put("todavía", "tiempo");
        diccionario.put("totalmente", "adverbio"); diccionario.put("trato", "sustantivo");
        diccionario.put("tu", "posesivo"); diccionario.put("tus", "posesivo");
        diccionario.put("un", "articulo"); diccionario.put("una", "articulo");
        diccionario.put("usuario", "sustantivo"); diccionario.put("usar", "accion");
        diccionario.put("vamos", "accion"); diccionario.put("voy", "accion");
        diccionario.put("vez", "tiempo"); diccionario.put("vea", "accion");
        diccionario.put("verse", "accion"); diccionario.put("volada", "estado");
        diccionario.put("y", "conector"); diccionario.put("ya", "tiempo");
        diccionario.put("yo", "pronombre"); diccionario.put("triste", "emocion");
        diccionario.put("feliz", "emocion"); diccionario.put("felicidades", "emocion");
        diccionario.put("aburrido", "emocion"); diccionario.put("aburrida", "emocion");
        diccionario.put("cansado", "emocion"); diccionario.put("cansada", "emocion");
        diccionario.put("cansancio", "estado"); diccionario.put("genial", "emocion");
        diccionario.put("mal", "emocion"); diccionario.put("malísima", "emocion");
        diccionario.put("malísimo", "emocion"); diccionario.put("malo", "emocion");
        diccionario.put("mala", "emocion"); diccionario.put("bien", "emocion");
        diccionario.put("bienestar", "estado"); diccionario.put("perro", "sustantivo");
        diccionario.put("perros", "sustantivo"); diccionario.put("mañana", "tiempo");
        diccionario.put("ayer", "tiempo"); diccionario.put("hoy", "tiempo");
        diccionario.put("siempre", "tiempo"); diccionario.put("pronto", "tiempo");
        diccionario.put("por qué", "interrogativo"); diccionario.put("quien", "interrogativo");
        diccionario.put("cuánto", "interrogativo"); diccionario.put("hacer", "accion");
        diccionario.put("harás", "accion"); diccionario.put("ir", "accion");
        diccionario.put("iré", "accion"); diccionario.put("irás", "accion");
        diccionario.put("ver", "accion"); diccionario.put("verás", "accion");
        diccionario.put("veré", "accion"); diccionario.put("escuchar", "accion");
        diccionario.put("escucharás", "accion"); diccionario.put("escucha", "accion");
        diccionario.put("contar", "accion"); diccionario.put("cuenta", "accion");
        diccionario.put("cuento", "accion"); diccionario.put("hambre", "estado");
        diccionario.put("sed", "estado"); diccionario.put("sueño", "estado");
        diccionario.put("enferma", "estado"); diccionario.put("enfermo", "estado");
        diccionario.put("salud", "estado"); diccionario.put("medicina", "estado");
        diccionario.put("medicamento", "sustantivo"); diccionario.put("medicamentos", "sustantivo");
        diccionario.put("comer", "accion"); diccionario.put("beber", "accion");
        diccionario.put("beberé", "accion"); diccionario.put("beberas", "accion");
        diccionario.put("dormir", "accion"); diccionario.put("dormiré", "accion");
        diccionario.put("dormirás", "accion"); diccionario.put("quedará", "estado");
        diccionario.put("quiere", "deseo"); diccionario.put("sí", "afirmacion");
        diccionario.put("claro", "afirmacion"); diccionario.put("obvio", "afirmacion");
        diccionario.put("obviamente", "adverbio"); diccionario.put("tal", "comparativo");
        diccionario.put("quizás", "duda"); diccionario.put("imposible", "duda");
        diccionario.put("difícil", "duda"); diccionario.put("difícilmente", "adverbio");
        diccionario.put("normal", "estado"); diccionario.put("normalmente", "adverbio");
        diccionario.put("fácil", "estado"); diccionario.put("fácilmente", "adverbio");
        diccionario.put("imposiblemente", "adverbio"); diccionario.put("correcto", "afirmacion");
        diccionario.put("incorrecto", "negacion"); diccionario.put("mío", "posesivo");
        diccionario.put("tuyo", "posesivo"); diccionario.put("suyo", "posesivo");
        diccionario.put("nuestro", "posesivo"); diccionario.put("alguien", "indefinido");
        diccionario.put("nadie", "indefinido"); diccionario.put("gente", "sustantivo");
        diccionario.put("persona", "sustantivo"); diccionario.put("amigo", "sustantivo");
        diccionario.put("amiga", "sustantivo"); diccionario.put("enemigo", "sustantivo");
        diccionario.put("amigos", "sustantivo"); diccionario.put("amigas", "sustantivo");
        diccionario.put("desconocido", "sustantivo"); diccionario.put("desconocida", "sustantivo");
        diccionario.put("desconocidos", "sustantivo"); diccionario.put("desconocidas", "sustantivo");
        diccionario.put("creada", "accion"); diccionario.put("creado", "accion");
        diccionario.put("creare", "accion"); diccionario.put("creación", "sustantivo");
        diccionario.put("tipo", "sustantivo"); diccionario.put("tipa", "sustantivo");
        diccionario.put("casa", "lugar"); diccionario.put("escuela", "lugar");
        diccionario.put("calle", "lugar"); diccionario.put("parque", "lugar");
        diccionario.put("trabajo", "lugar"); diccionario.put("cuarto", "lugar");
        diccionario.put("ciudad", "lugar"); diccionario.put("aquí", "lugar");
        diccionario.put("allá", "lugar"); diccionario.put("lejos", "lugar");
        diccionario.put("cerca", "lugar"); diccionario.put("departamento", "lugar");
        diccionario.put("cafetería", "lugar"); diccionario.put("bar", "lugar");
        diccionario.put("restaurante", "lugar"); diccionario.put("cine", "lugar");
        diccionario.put("prostíbulo", "lugar"); diccionario.put("antro", "lugar");
        diccionario.put("país", "lugar"); diccionario.put("nombre", "sustantivo");
        diccionario.put("llamo", "accion"); diccionario.put("llame", "accion");
        diccionario.put("venir", "accion"); diccionario.put("vendré", "accion");
        diccionario.put("vendrás", "accion"); diccionario.put("vendría", "accion");
        diccionario.put("entrar", "accion"); diccionario.put("entraré", "accion");
        diccionario.put("entre", "preposicion"); diccionario.put("sali", "accion");
        diccionario.put("saliste", "accion"); diccionario.put("salir", "accion");
        diccionario.put("subir", "accion"); diccionario.put("subiré", "accion");
        diccionario.put("subirá", "accion"); diccionario.put("bajar", "accion");
        diccionario.put("bajara", "accion"); diccionario.put("bajaré", "accion");
        diccionario.put("baje", "accion"); diccionario.put("izquierda", "posicion");
        diccionario.put("derecha", "posicion"); diccionario.put("arriba", "posicion");
        diccionario.put("adelante", "posicion"); diccionario.put("atrás", "posicion");
        diccionario.put("cuáles", "interrogativo"); diccionario.put("acaso", "duda");
        diccionario.put("mucho", "cantidad"); diccionario.put("muchísimo", "cantidad");
        diccionario.put("mucha", "cantidad"); diccionario.put("muchísima", "cantidad");
        diccionario.put("muchísimas", "cantidad"); diccionario.put("muchísimos", "cantidad");
        diccionario.put("poco", "cantidad"); diccionario.put("poca", "cantidad");
        diccionario.put("poquito", "cantidad"); diccionario.put("poquitito", "cantidad");
        diccionario.put("poquita", "cantidad"); diccionario.put("poquitita", "cantidad");
        diccionario.put("bastante", "cantidad"); diccionario.put("algunos", "indefinido");
        diccionario.put("algunas", "indefinido"); diccionario.put("ninguno", "negacion");
        diccionario.put("ninguna", "negacion"); diccionario.put("ni", "negacion");
        diccionario.put("ne", "negacion"); diccionario.put("todo", "totalidad");
        diccionario.put("toda", "totalidad"); diccionario.put("nada", "negacion");
        diccionario.put("nadita", "negacion"); diccionario.put("nadota", "negacion");
        diccionario.put("gracias", "cortesia"); diccionario.put("porfa", "cortesia");
        diccionario.put("porfis", "cortesia"); diccionario.put("perdón", "cortesia");
        diccionario.put("perdóname", "cortesia"); diccionario.put("perdóneme", "cortesia");
        diccionario.put("disculpa", "cortesia"); diccionario.put("disculpame", "cortesia");
        diccionario.put("discúlpeme", "cortesia"); diccionario.put("adiós", "cortesia");
        diccionario.put("bay", "cortesia"); diccionario.put("hasta", "cortesia");
        diccionario.put("luego", "tiempo"); diccionario.put("entendi", "cognitivo");
        diccionario.put("dijiste", "accion"); diccionario.put("explicarme", "accion");
        diccionario.put("otras", "indefinido"); diccionario.put("eso", "demostrativo");
        diccionario.put("esa", "demostrativo"); diccionario.put("refieres", "accion");
        diccionario.put("refiero", "accion"); diccionario.put("refería", "accion");
        diccionario.put("referí", "accion"); diccionario.put("tokens", "tecnico");
        diccionario.put("etiquetas", "tecnico"); diccionario.put("veamos", "accion");
        diccionario.put("besos", "cortesia"); diccionario.put("besar", "accion");
    }

    public String procesar(String entrada) {
        String[] tokens = entrada.toLowerCase().split(" ");
        for (String t : tokens) {
            if (diccionario.containsKey(t)) {
                String etiqueta = diccionario.get(t);
                // Lógica de pesos: +5 para emociones, -5 para negaciones, +1 para resto
                if (etiqueta.equals("emocion")) score += 5;
                else if (etiqueta.equals("negacion")) score -= 5;
                else score += 1;
            }
        }
        return "Score actual: " + score;
    }
                        }
